<?php

namespace Lo\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OauthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OauthRepository extends EntityRepository
{
}
